bip/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

from bip import views



app_name = 'bip'


urlpatterns = [

    # case manager and data entry urls for login and access-----------------
    



    
    path('afterlogin', views.afterlogin_view,name='afterlogin'),

    path('case_manager_signup/', views.case_manager_signup_view,name='case_manager_signup'),
    
    path('case_manager_login/', LoginView.as_view(template_name='account/case_manager_login.html'),name='case_manager_login'),

    
    path('data_entry_signup/', views.data_entry_signup_view, name='data_entry_signup'),
    path('data_entry_login/', LoginView.as_view(template_name='account/data_entry_login.html'), name='data_entry_login'),
    

    path('data_entry_dashboard', views.data_entry_dashboard_view,name='data_entry_dashboard'),

    path('casemanagerclick', views.casemangerclick_view),
    path('dataentryclick', views.dataentryclick_view),

    path('data_entry_input/<pk>/', views.data_entry_input_view, name='data_entry_input'),

    path('case_manager_dashboard/<int:pk>', views.case_manager_dashboard_view,name='case_manager_dashboard'),

    path('admin_data_entry_approve/<int:pk>', views.admin_approve_data_entry_view,name='admin_data_entry_approve'),
    
    path('approved_data_entry/<int:pk>', views.approved_data_entry_view,name='approved_data_entry'),
    
    path('admin_delete_data_entry/<int:pk>', views.admin_delete_data_entry_view,name='admin_delete_data_entry'),
    
    path('delete_data_entry/<int:pk>', views.delete_data_entry_view,name='delete_data_entry'),

    path('reject_data_entry/<int:pk>', views.reject_data_entry_view,name='reject_data_entry'),
    
   
    path('assign_data_entry/<pk>/', views.assign_data_entry, name='assign_data_entry'),
    
    path('updateunique_case_identifier/<pk>/', views.updateunique_case_identifier, name='updateunique_case_identifier'),
    

    path('case_manager_unique_identifier/<pk>/', views.case_manager_unique_identifier, name='case_manager_unique_identifier'),
    



    path('reset_password/', auth_views.PasswordResetView.as_view(template_name= 'account/password_reset.html'), 
         name='reset_password'),

   
   

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_sent.html'),
          name='password_reset_done'),


    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form.html'), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'), name='password_reset_complete'),

    
    # the core of the website--------------------------------
    
    path('home/', views.HomePage.as_view(), name="home"),


    path('luna/', views.luna, name="luna"),
    path('additional_notes/', views.additional_notes_view, name="additional_notes"),

    
    path('statistics/<pk>/', views.statistics, name="statistics"),

    path('', views.description_view, name="description"),

    
    path('student_list/<pk>/', views.list_view, name='student_list'),

    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    
    path('dashboard/<pk>/', views.dashboard, name='dashboard'),
    
    path('create_incident/<pk>/', views.behavior_form_view, name='create_incident'),
    
    path('updatepost/<int:pk>/<int:student_id>/', views.updatePost, name='updatepost'),

    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),

    path('delete_post/<pk>/', views.deletePost, name='delete_post'),
        
    path('create_student/', views.create_student, name='create_student'),
    
    
    path('update_student/<pk>/',views.updateStudent,name='update_student'),
    
    
    path('delete_student/<pk>/',views.deleteStudent,name='delete_student'),
     
    path('delete_user/<pk>/',views.deleteUser,name='delete_user'),

    path('user_account/<pk>/',views.user_account,name='user_account'),


    path('create_unique_id/<pk>/',views.create_unique_id,name='create_unique_id'),

    path('case_profile/<pk>/',views.student_profile,name='student_profile'),

    
    path('create_behavior/<pk>/', views.create_behavior, name='create_behavior'),
    path('update_behavior/<pk>/',views.updateBehavior,name='update_behavior'),
    path('delete_behavior/<pk>/', views.deleteBehavior, name='delete_behavior'),
    

    path('edit_behavior/<pk>/', views.edit_behavior_view, name='edit_behavior'),
    path('edit_anticedent/<pk>/', views.edit_anticedent_view, name='edit_anticedent'),
    path('edit_consequence/<pk>/', views.edit_consequence_view, name='edit_consequence'),
    path('edit_function/<pk>/', views.edit_function_view, name='edit_function'),


    path('create_anticedent/<pk>/', views.create_anticedent, name='create_anticedent'),
    path('update_anticedent/<pk>/',views.updateAnticedent,name='update_anticedent'),
    path('delete_anticedent/<pk>/', views.deleteAnticedent, name='delete_anticedent'),
    
    
    path('create_function/<pk>/', views.create_function, name='create_function'),
    
    path('update_function/<pk>/',views.updatFunction,name='update_function'),
    
    path('delete_function/<pk>/', views.deleteFunction, name='delete_function'),
    
    
    
    
    path('create_consequence/<pk>/', views.create_consequence, name='create_consequence'),
     
    path('update_consequence/<pk>/',views.updateConsequence,name='update_consequence'),
    path('delete_consequence/<pk>/', views.deleteConsequence, name='delete_consequence'),
    
    path('create_setting/<pk>/', views.create_setting_view, name='create_setting'),
    path('update_setting/<pk>/',views.updateSetting,name='update_setting'),
    path('edit_setting/<pk>/', views.edit_enviroment_view, name='edit_setting'),
    path('delete_setting/<pk>/', views.deleteEnviroment, name='delete_setting'),

    path('error_page/<pk>/', views.error_page, name='error_page'),

    path('correlation/<pk>/', views.correlation_view, name='correlation'),
    path('pie_charts/<pk>/', views.pie_chart_view, name='pie_charts'),


    path('snapshot/<pk>/', views.snapshot_view, name='snapshot'),
    path('snapshot_data_entry/<pk>/', views.snapshot_data_entry_view, name='snapshot_data_entry'),

    
    path('function/<pk>/', views.function_view, name='function'),
    path('consequence/<pk>/', views.consequence_view, name='consequence'),


    # path('machine_learning/<pk>/', views.train_naive_bayes, name='machine_learning'),

    path('download_chart_pdf/<pk>/', views.download_chart_pdf, name='download_chart_pdf'),

    path('download_antecedent_chart_pdf/<pk>/', views.download_antecedent_chart_pdf, name='download_antecedent_chart_pdf'),

    path('download_consequence_chart_pdf/<pk>/', views.download_consequence_chart_pdf, name='download_consequence_chart_pdf'),
    
    
    
    path('download_function_chart_pdf/<pk>/', views.download_function_chart_pdf, name='download_function_chart_pdf'),

    path('anticedent/<pk>/', views.anticedent_view, name='anticedent'),

    path('setting/<pk>/', views.enviroment_view, name='setting'),

    
    
    path('filter_data/<pk>/', views.filter_data, name='filter_data'),
    
    
    
    path('chart/<pk>/', views.chart_view, name='chart'),



    path('raw_data/<pk>/', views.raw_data, name='raw_data'),

    path('export/<pk>/', views.export, name='export'),


    path('upload_page/<pk>/', views.upload_page, name='upload_page'),
    path('case_upload_csv/', views.case_upload_csv, name='case_upload_csv'),  
    path('upload_options/<pk>/', views.upload_options, name='upload_options'),
    path('case_upload_csv_duration/', views.case_upload_csv_duration, name='case_upload_csv_duration'),  
    path('case_upload_csv_time/', views.case_upload_csv_time, name='case_upload_csv_time'),  
    path('case_upload_csv_multiple/', views.case_upload_csv_multiple, name='case_upload_csv_multiple'),  


    
    path('download_page/', views.download_page, name='download_page'),

    # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("logout/", views.user_logout, name="logout"),


  
    path('video/', views.show_video, name='show_video'),

    path('contingency_view/<pk>/', views.contingency_view, name='contingency_view'),
    path('contingency_view_function/<pk>/', views.contingency_view_function, name='contingency_view_function'),
    path('setting_table/<pk>/', views.contingency_view_setting, name='setting_table'),

    path('donations/', views.donations, name="donations"),

    # artificial inttelligence urls--------------------------------
    path('function_ai_abc/<pk>/', views.function_ai_abc, name='function_ai_abc'),
    path('antecedent_ai/<pk>/', views.antecedent_ai, name='antecedent_ai'),
    path('intervention_ai_abc/<pk>/', views.intervention_ai_abc, name='intervention_ai_abc'),
    path('goals_ai/<pk>/', views.goals_ai, name='goals_ai'),
    path('bsp/<pk>/', views.bsp, name='bsp'),
    path('enviromental_bsp_ai/<pk>/', views.enviromental_bsp_ai, name='enviromental_bsp_ai'),
    path('replacement_bsp_ai/<pk>/', views.replacement_bsp_ai, name='replacement_bsp_ai'),
    path('reinforcement_ai_abc/<pk>/', views.reinforcement_ai_abc, name='reinforcement_ai_abc'),




]

functional_behavior_analysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from bip import views
from django.views.static import serve 

from django.urls import re_path


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('bip.urls')),
    path('', include('django.contrib.auth.urls'))

   

  
]

bip/forms.py
from django import forms
from django.contrib.auth.models import User
from bip import models
from django.forms import ModelForm
from .models import  Case, Behavior, Function, Student,Anticedent,Consequence, Enviroment,CustomUser
from django import forms
# from accounts.models import MyUser
from django.core.exceptions import ValidationError





class CaseManagerUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)  # Makes the email field explicitly required
    confirm_email = forms.EmailField(required=True)  # Add confirm email field

    password = forms.CharField(widget=forms.PasswordInput())
    password_confirmation = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username','bio', 'email', ]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("This field is required.")
        # Here, you might want to check if the email already exists in the database
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")

        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if email and confirm_email and email != confirm_email:
            self.add_error('confirm_email', "The two email fields didn't match.")

        if password and password_confirmation and password != password_confirmation:
            self.add_error('password_confirmation', "The two password fields didn't match.")

        return cleaned_data
    

class CaseManagerForm(forms.ModelForm):

    
    class Meta:
        model=models.CaseManager
        fields=['slug','status']

class UpdateCaseManagerForm(forms.ModelForm):
    class Meta:
        model=models.CaseManager
        fields=['slug',]

#for teacher related form
        
class DataEntryUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label="Password")
    password_confirmation = forms.CharField(widget=forms.PasswordInput(), label="Confirm Password")

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'password', 'bio', 'email']
        

class DataEntryForm(forms.ModelForm):
   

    assignedCaseManagerSlug=forms.CharField(max_length=20,required=False)
    assignedStudentSlug=forms.CharField(max_length=20,required=False)

    class Meta:
        model=models.DataEntry
        fields=['status']


# Behaviorforms-----------------------------------------------------------------------------

class DateInput(forms.DateInput):
    input_type = 'date'

class BehaviorForm(forms.ModelForm):
 
    class Meta():
        model = Case
        fields = ('behavior','anticedent','consequence','function','date_created','time','duration','frequency','intensity','enviroment')
        widgets = {
            'date_created': DateInput(),
            'behavior':forms.RadioSelect(),
            'anticedent':forms.RadioSelect(),
            'function':forms.RadioSelect(),
            'consequence':forms.RadioSelect(),
            'enviroment': forms.Select(),  
            'time': forms.TimeInput(attrs={'placeholder': '12:00', 'type': 'time'}),

        }

   
class StudentForm(ModelForm):
    class Meta():
        model = Student
        fields = ('studentname','age','grade','nonverbal') 
        
        
class StudentUpdateForm(ModelForm):
    class Meta():
        model = Student
        fields = ('studentname','slug','age','grade','nonverbal') 
 
class StudentFormSlug(ModelForm):
    class Meta():
        model = Student
        fields = ('slug',) 
        
class CreateBehaviorForm(ModelForm):
    class Meta():
        model = Behavior
        fields = ('behaviorincident','behavior_definition','intensity_definition') 
        widgets = {
            'intensity_definition': forms.Textarea(attrs={'rows': 3, 'cols': 40}),
        }

class CreateAnticedentForm(ModelForm):
    class Meta():
        model = Anticedent
        fields = ('anticedentincident','anticedent_definition') 
 
class CreateFunctionForm(ModelForm):
    class Meta():
        model = Function
        fields = ('behaviorfunction',) 
 
  
class CreateConsequenceForm(ModelForm):
    class Meta():
        model = Consequence
        fields = ('behaviorconsequence',) 



class CreateEnviromentForm(ModelForm):
    class Meta():
        model = Enviroment
        fields = ('behaviorenviroment',)

class StudentBehaviorForm(ModelForm):
    class Meta():
        model = Behavior
        fields = '__all__'    
        
FORMAT_CHOICES ={
    ('xlsx', 'xlsx'),
    ('csv', 'csv'),
    ('json', 'json'),
}




class FormatForm(forms.Form):
    format = forms.ChoiceField(choices=FORMAT_CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))




class CsvUploadForm(forms.Form):
    csv_file = forms.FileField(label='Select a CSV file')

bip/templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"crossorigin="anonymous"
    />
    <!-- semantic UI -->

    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <script src="https://kit.fontawesome.com/0e1798cd98.js" crossorigin="anonymous"></script>
   


    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %} ">
  </head>
  <body>
    {% load crispy_forms_tags %}

    {% include 'partials/nav.html'%} {% block content %} {% endblock %}


    <script type='text/javascript'  {% static 'main.js' %}></script>
   
  </body>

    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
      crossorigin="anonymous"
    ></script>
</html>

bip/templates/partials/nav.html
{% load custom_filters %}


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="css/style.css"> -->
  <title>EFBA</title>
</head>

<!-- <body data-spy="scroll" data-target="#main-nav" id="home"> -->
  <nav class="navbar navbar-expand-sm navbar-dark fixed-top custom-navbar-bg" id="main-nav">
    {% if user.is_authenticated  %} 

    
    <div class="container">
<span class="navbar-brand">EFBA ({{ user.username }})</span>
      <a href="{% url 'bip:logout' %}" class="nav-link text-white">Log Out</a>

      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
         
          {% if user|is_case_manager %}

          <li class="nav-item">
            <a href="{% url 'bip:create_student' %}" class="nav-link text-white">Add Case</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'bip:for_user' username=user.username %}" class="nav-link text-white">Case List</a>
          </li>
          {% endif %}
          <!-- <li class="nav-item">
            <a href="{% url 'bip:logout' %}" class="nav-link">Log Out</a>
          </li> -->
          {% else %}
          <nav class="navbar navbar-expand-sm navbar-dark fixed-top custom-navbar-bg" id="main-nav">
            <a href="" class="navbar-brand">Exploratory FBA</a>


          
        </ul>
      </div>
    </div>
   
  </nav>

        {% endif %} 

      </div>
    </div>
   
  </nav>
        


  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>


<style>
    .custom-navbar-bg {
    background-color: #339933; /* Expanded form of #393 */
}

</style>