bip/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

from bip import views



app_name = 'bip'


urlpatterns = [

    # case manager and data entry urls for login and access-----------------
    



    
    path('afterlogin', views.afterlogin_view,name='afterlogin'),

    path('case_manager_signup/', views.case_manager_signup_view,name='case_manager_signup'),
    
    path('case_manager_login/', LoginView.as_view(template_name='account/case_manager_login.html'),name='case_manager_login'),

    
    path('data_entry_signup/', views.data_entry_signup_view, name='data_entry_signup'),
    path('data_entry_login/', LoginView.as_view(template_name='account/data_entry_login.html'), name='data_entry_login'),
    

    path('data_entry_dashboard', views.data_entry_dashboard_view,name='data_entry_dashboard'),

    path('casemanagerclick', views.casemangerclick_view),
    path('dataentryclick', views.dataentryclick_view),

    path('data_entry_input/<pk>/', views.data_entry_input_view, name='data_entry_input'),

    path('case_manager_dashboard/<int:pk>', views.case_manager_dashboard_view,name='case_manager_dashboard'),

    path('admin_data_entry_approve/<int:pk>', views.admin_approve_data_entry_view,name='admin_data_entry_approve'),
    
    path('approved_data_entry/<int:pk>', views.approved_data_entry_view,name='approved_data_entry'),
    
    path('admin_delete_data_entry/<int:pk>', views.admin_delete_data_entry_view,name='admin_delete_data_entry'),
    
    path('delete_data_entry/<int:pk>', views.delete_data_entry_view,name='delete_data_entry'),

    path('reject_data_entry/<int:pk>', views.reject_data_entry_view,name='reject_data_entry'),
    
   
    path('assign_data_entry/<pk>/', views.assign_data_entry, name='assign_data_entry'),
    
    path('updateunique_case_identifier/<pk>/', views.updateunique_case_identifier, name='updateunique_case_identifier'),
    

    path('case_manager_unique_identifier/<pk>/', views.case_manager_unique_identifier, name='case_manager_unique_identifier'),
    



    path('reset_password/', auth_views.PasswordResetView.as_view(template_name= 'account/password_reset.html'), 
         name='reset_password'),

   
   

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_sent.html'),
          name='password_reset_done'),


    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_form.html'), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'), name='password_reset_complete'),

    
    # the core of the website--------------------------------
    
    path('home/', views.HomePage.as_view(), name="home"),


    path('luna/', views.luna, name="luna"),
    path('additional_notes/', views.additional_notes_view, name="additional_notes"),

    
    path('statistics/<pk>/', views.statistics, name="statistics"),

    path('', views.description_view, name="description"),

    
    path('student_list/<pk>/', views.list_view, name='student_list'),

    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    
    path('dashboard/<pk>/', views.dashboard, name='dashboard'),
    
    path('create_incident/<pk>/', views.behavior_form_view, name='create_incident'),
    
    path('updatepost/<int:pk>/<int:student_id>/', views.updatePost, name='updatepost'),

    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),

    path('delete_post/<pk>/', views.deletePost, name='delete_post'),
        
    path('create_student/', views.create_student, name='create_student'),
    
    
    path('update_student/<pk>/',views.updateStudent,name='update_student'),
    
    
    path('delete_student/<pk>/',views.deleteStudent,name='delete_student'),
     
    path('delete_user/<pk>/',views.deleteUser,name='delete_user'),

    path('user_account/<pk>/',views.user_account,name='user_account'),


    path('create_unique_id/<pk>/',views.create_unique_id,name='create_unique_id'),

    path('case_profile/<pk>/',views.student_profile,name='student_profile'),

    
    path('create_behavior/<pk>/', views.create_behavior, name='create_behavior'),
    path('update_behavior/<pk>/',views.updateBehavior,name='update_behavior'),
    path('delete_behavior/<pk>/', views.deleteBehavior, name='delete_behavior'),
    

    path('edit_behavior/<pk>/', views.edit_behavior_view, name='edit_behavior'),
    path('edit_anticedent/<pk>/', views.edit_anticedent_view, name='edit_anticedent'),
    path('edit_consequence/<pk>/', views.edit_consequence_view, name='edit_consequence'),
    path('edit_function/<pk>/', views.edit_function_view, name='edit_function'),


    path('create_anticedent/<pk>/', views.create_anticedent, name='create_anticedent'),
    path('update_anticedent/<pk>/',views.updateAnticedent,name='update_anticedent'),
    path('delete_anticedent/<pk>/', views.deleteAnticedent, name='delete_anticedent'),
    
    
    path('create_function/<pk>/', views.create_function, name='create_function'),
    
    path('update_function/<pk>/',views.updatFunction,name='update_function'),
    
    path('delete_function/<pk>/', views.deleteFunction, name='delete_function'),
    
    
    
    
    path('create_consequence/<pk>/', views.create_consequence, name='create_consequence'),
     
    path('update_consequence/<pk>/',views.updateConsequence,name='update_consequence'),
    path('delete_consequence/<pk>/', views.deleteConsequence, name='delete_consequence'),
    
    path('create_setting/<pk>/', views.create_setting_view, name='create_setting'),
    path('update_setting/<pk>/',views.updateSetting,name='update_setting'),
    path('edit_setting/<pk>/', views.edit_enviroment_view, name='edit_setting'),
    path('delete_setting/<pk>/', views.deleteEnviroment, name='delete_setting'),

    path('error_page/<pk>/', views.error_page, name='error_page'),

    path('correlation/<pk>/', views.correlation_view, name='correlation'),
    path('pie_charts/<pk>/', views.pie_chart_view, name='pie_charts'),


    path('snapshot/<pk>/', views.snapshot_view, name='snapshot'),
    path('snapshot_data_entry/<pk>/', views.snapshot_data_entry_view, name='snapshot_data_entry'),

    
    path('function/<pk>/', views.function_view, name='function'),
    path('consequence/<pk>/', views.consequence_view, name='consequence'),


    # path('machine_learning/<pk>/', views.train_naive_bayes, name='machine_learning'),

    path('download_chart_pdf/<pk>/', views.download_chart_pdf, name='download_chart_pdf'),

    path('download_antecedent_chart_pdf/<pk>/', views.download_antecedent_chart_pdf, name='download_antecedent_chart_pdf'),

    path('download_consequence_chart_pdf/<pk>/', views.download_consequence_chart_pdf, name='download_consequence_chart_pdf'),
    
    
    
    path('download_function_chart_pdf/<pk>/', views.download_function_chart_pdf, name='download_function_chart_pdf'),

    path('anticedent/<pk>/', views.anticedent_view, name='anticedent'),

    path('setting/<pk>/', views.enviroment_view, name='setting'),

    
    
    path('filter_data/<pk>/', views.filter_data, name='filter_data'),
    
    
    
    path('chart/<pk>/', views.chart_view, name='chart'),



    path('raw_data/<pk>/', views.raw_data, name='raw_data'),

    path('export/<pk>/', views.export, name='export'),


    path('upload_page/<pk>/', views.upload_page, name='upload_page'),
    path('case_upload_csv/', views.case_upload_csv, name='case_upload_csv'),  
    path('upload_options/<pk>/', views.upload_options, name='upload_options'),
    path('case_upload_csv_duration/', views.case_upload_csv_duration, name='case_upload_csv_duration'),  
    path('case_upload_csv_time/', views.case_upload_csv_time, name='case_upload_csv_time'),  
    path('case_upload_csv_multiple/', views.case_upload_csv_multiple, name='case_upload_csv_multiple'),  


    
    path('download_page/', views.download_page, name='download_page'),

    # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("logout/", views.user_logout, name="logout"),


  
    path('video/', views.show_video, name='show_video'),

    path('contingency_view/<pk>/', views.contingency_view, name='contingency_view'),
    path('contingency_view_function/<pk>/', views.contingency_view_function, name='contingency_view_function'),
    path('setting_table/<pk>/', views.contingency_view_setting, name='setting_table'),

    path('donations/', views.donations, name="donations"),

    # artificial inttelligence urls--------------------------------
    path('function_ai_abc/<pk>/', views.function_ai_abc, name='function_ai_abc'),
    path('antecedent_ai/<pk>/', views.antecedent_ai, name='antecedent_ai'),
    path('intervention_ai_abc/<pk>/', views.intervention_ai_abc, name='intervention_ai_abc'),
    path('goals_ai/<pk>/', views.goals_ai, name='goals_ai'),
    path('bsp/<pk>/', views.bsp, name='bsp'),
    path('enviromental_bsp_ai/<pk>/', views.enviromental_bsp_ai, name='enviromental_bsp_ai'),
    path('replacement_bsp_ai/<pk>/', views.replacement_bsp_ai, name='replacement_bsp_ai'),
    path('reinforcement_ai_abc/<pk>/', views.reinforcement_ai_abc, name='reinforcement_ai_abc'),




]

functional_behavior_analysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from bip import views
from django.views.static import serve 

from django.urls import re_path


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('bip.urls')),
    path('', include('django.contrib.auth.urls'))

   

  
]

bip/forms.py
from django import forms
from django.contrib.auth.models import User
from bip import models
from django.forms import ModelForm
from .models import  Case, Behavior, Function, Student,Anticedent,Consequence, Enviroment,CustomUser
from django import forms
# from accounts.models import MyUser
from django.core.exceptions import ValidationError





class CaseManagerUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)  # Makes the email field explicitly required
    confirm_email = forms.EmailField(required=True)  # Add confirm email field

    password = forms.CharField(widget=forms.PasswordInput())
    password_confirmation = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username','bio', 'email', ]

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("This field is required.")
        # Here, you might want to check if the email already exists in the database
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")

        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if email and confirm_email and email != confirm_email:
            self.add_error('confirm_email', "The two email fields didn't match.")

        if password and password_confirmation and password != password_confirmation:
            self.add_error('password_confirmation', "The two password fields didn't match.")

        return cleaned_data
    

class CaseManagerForm(forms.ModelForm):

    
    class Meta:
        model=models.CaseManager
        fields=['slug','status']

class UpdateCaseManagerForm(forms.ModelForm):
    class Meta:
        model=models.CaseManager
        fields=['slug',]

#for teacher related form
        
class DataEntryUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput(), label="Password")
    password_confirmation = forms.CharField(widget=forms.PasswordInput(), label="Confirm Password")

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'password', 'bio', 'email']
        

class DataEntryForm(forms.ModelForm):
   

    assignedCaseManagerSlug=forms.CharField(max_length=20,required=False)
    assignedStudentSlug=forms.CharField(max_length=20,required=False)

    class Meta:
        model=models.DataEntry
        fields=['status']


# Behaviorforms-----------------------------------------------------------------------------

class DateInput(forms.DateInput):
    input_type = 'date'

class BehaviorForm(forms.ModelForm):
 
    class Meta():
        model = Case
        fields = ('behavior','anticedent','consequence','function','date_created','time','duration','frequency','intensity','enviroment')
        widgets = {
            'date_created': DateInput(),
            'behavior':forms.RadioSelect(),
            'anticedent':forms.RadioSelect(),
            'function':forms.RadioSelect(),
            'consequence':forms.RadioSelect(),
            'enviroment': forms.Select(),  
            'time': forms.TimeInput(attrs={'placeholder': '12:00', 'type': 'time'}),

        }

   
class StudentForm(ModelForm):
    class Meta():
        model = Student
        fields = ('studentname','age','grade','nonverbal') 
        
        
class StudentUpdateForm(ModelForm):
    class Meta():
        model = Student
        fields = ('studentname','slug','age','grade','nonverbal') 
 
class StudentFormSlug(ModelForm):
    class Meta():
        model = Student
        fields = ('slug',) 
        
class CreateBehaviorForm(ModelForm):
    class Meta():
        model = Behavior
        fields = ('behaviorincident','behavior_definition','intensity_definition') 
        widgets = {
            'intensity_definition': forms.Textarea(attrs={'rows': 3, 'cols': 40}),
        }

class CreateAnticedentForm(ModelForm):
    class Meta():
        model = Anticedent
        fields = ('anticedentincident','anticedent_definition') 
 
class CreateFunctionForm(ModelForm):
    class Meta():
        model = Function
        fields = ('behaviorfunction',) 
 
  
class CreateConsequenceForm(ModelForm):
    class Meta():
        model = Consequence
        fields = ('behaviorconsequence',) 



class CreateEnviromentForm(ModelForm):
    class Meta():
        model = Enviroment
        fields = ('behaviorenviroment',)

class StudentBehaviorForm(ModelForm):
    class Meta():
        model = Behavior
        fields = '__all__'    
        
FORMAT_CHOICES ={
    ('xlsx', 'xlsx'),
    ('csv', 'csv'),
    ('json', 'json'),
}




class FormatForm(forms.Form):
    format = forms.ChoiceField(choices=FORMAT_CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))




class CsvUploadForm(forms.Form):
    csv_file = forms.FileField(label='Select a CSV file')

bip/templates/bip/dashboard.html
{% extends 'partials/base.html' %} 
{% block content %}

<br>
<div class="container my-4">
  <!-- Navigation Button -->
  <title>EFBA</title>

  <div class="nav-button">
    <a class="btn btn-outline-info" href="{% url 'bip:create_incident' student.id %}"> <b> Log Behavior for {{student.studentname}}</b></a>
  </div>
  

<div class="row">
  <div class="col-md">
    <div class="card card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Create Form</h5>
        <p class="card-text">Must Create Behavior, Antecedent, and Function  before Logging Behavior:
        </p>
              <ul class="list-group list-group-flush">
                      <li class="list-group-item"><a  href="{% url 'bip:create_behavior' student.id %}" class="card-link">Behavior/</a><a href="{% url 'bip:edit_behavior' student.id %}" >Edit</a></li>
                      <li class="list-group-item"><a href="{% url 'bip:create_anticedent' student.id %}" class="card-link">Antecedent/</a><a href="{% url 'bip:edit_anticedent' student.id %}">Edit</a></li>
                      <li class="list-group-item"><a href="{% url 'bip:create_consequence' student.id %}" class="card-link">Consequence/</a><a href="{% url 'bip:edit_consequence' student.id %}">Edit</a></li>
                      <li class="list-group-item"><a  href="{% url 'bip:create_function' student.id %}" class="card-link">Function/</a><a  href="{% url 'bip:edit_function' student.id %}">Edit</a></li>
                      <li class="list-group-item"><a  href="{% url 'bip:create_setting' student.id %}" class="card-link">Setting</a>/<a  href="{% url 'bip:edit_setting' student.id %}">Edit</a></li> 
                      <li class="list-group-item"><a  href="{% url 'bip:student_profile' student.id %}" class="card-link">Case</a></li> 

                  
              </ul>
    </div>
  </div>
</div> 

 
  <div class="col-md">
    <div class="card card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Exploratory Data Analysis</h5>
        <p class="card-text"> Data Visualization,  Data Analysis and AI generated BSP.</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="{% url 'bip:snapshot' student.id %}" class="card-link">Behavior</a></li>
        <li class="list-group-item"><a href="{% url 'bip:anticedent' student.pk %}" class="card-link">Antecedent</a></li>
        <li class="list-group-item"><a href="{% url 'bip:consequence' student.pk %}" class="card-link">Consequence</a></li>
        <li class="list-group-item"><a href="{% url 'bip:function' student.pk %}" class="card-link">Function</a> </li>
        <li class="list-group-item"><a href="{% url 'bip:setting' student.pk %}" class="card-link">Setting</a></li>
       <li class="list-group-item"><a a href="{% url 'bip:filter_data' student.id %}" class="card-link">Filter Data</a></li>  
       <li class="list-group-item"><a a href="{% url 'bip:bsp' student.id %}" class="card-link">AI-Behavior Support Plan</a></li>  

      </ul>
   
    </div>
  </div> 

  <div class="col-md">
    <div class="card card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Overview</h5>
        <p class="card-text">Download data as csv file for excel, numbers, google sheet; Assign a Data Collector.</p>
      </div>
      {% comment %} <ul class="list-group list-group-flush">
        <li class="list-group-item"><a href="#" class="card-link">Visual Spreadsheet</a></li> {% endcomment %}
        <li class="list-group-item"><a a href="{% url 'bip:raw_data' student.id %}" class="card-link">Data Tables</a></li>  
        <li class="list-group-item"><a href="{% url 'bip:export' student.id %}" class="card-link">Download Spreadsheet</a></li>
        <!-- <li class="list-group-item"><a href="{% url 'bip:upload_options' student.id %}" class="card-link">Upload CSV file</a></li> -->

    
       <li class="list-group-item"><a  href="{% url 'bip:assign_data_entry' student.id %}">Add Data Collector</a></li> 
      </ul>
    
    </div>
  </div>
</div>


{% comment %} Use this for html of form below {% endcomment %}
<br>
<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <table class="table table-striped">
        <tr>
          <th>Behavior(<a  data-toggle="popover" data-placement="top" data-content="Why Frequency? 
            To count the number of times the same behavior occured within one incident 
            (ie. headbanging, hitting etc.)."><span style="color: blue;">Frequency</span></a>)</th>
          <th>Antecedent</th>
          <th>Consequence</th>
          <th>Function</th>
          
          
          
          {% if student_enviroment %}
          <th>Setting</th>
          {% endif %}


          <th>Intensity</th>
          
          {% if student_time %}

        <th>Time</th>
        {% endif %}


        {% if student_duration %}

        <th>Duration</th>
        {% endif %}

        <!-- Display the duration value here -->
          <th>Date</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for incident in student_behaviors %}
        <tr>
    
          <td>{{incident.behavior }}({{incident.frequency }})</td>
          <td>{{incident.anticedent}}</td>
          <td>{{incident.consequence}}</td>
          <td>{{incident.function}}</td>
          {% if incident.enviroment%}
          <td>{{incident.enviroment}}</td>
          {% endif %}
          {% if incident.intensity %}
          <td>{{incident.intensity}}</td>
          {% endif %}
          {% if incident.time %}
          <td>{{incident.time}}</td>
          {% endif %}


          

          {% if incident.duration%}
          <td>{{incident.time_change}}</td>
          {% endif %}

          <td>{{incident.date_created|date:'m-d-Y'}}</td> 

          <td> <a class="btn btn-warning" href="{% url 'bip:updatepost' pk=incident.pk student_id=incident.student_id %}" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg></a></td> 



          <td> <a class="btn btn-danger" href="{% url 'bip:delete_post' pk=incident.pk  %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal-x" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M6.146 6.146a.5.5 0 0 1 .708 0L8 7.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 8l1.147 1.146a.5.5 0 0 1-.708.708L8 8.707 6.854 9.854a.5.5 0 0 1-.708-.708L7.293 8 6.146 6.854a.5.5 0 0 1 0-.708z"/>
            <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
            <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
          </svg></a></td>  
           
           {% endfor%}

        </tr>
      </table>
    </div>
  </div>
</div>




</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
crossorigin="anonymous"></script>
<script>
// Init Popover
$('[data-toggle="popover"]').popover();

function showPopover() {
  $('#hello').popover('show');
}

function hidePopover() {
  $('#hello').popover('hide');
}

function togglePopover() {
  $('#hello').popover('toggle');
}

// Popover events
$('#hello').on('show.bs.popover', function () {
  console.log('Popover show');
});

$('#hello').on('shown.bs.popover', function () {
  console.log('Popover shown');
});

$('#hello').on('hide.bs.popover', function () {
  console.log('Popover hide');
});

$('#hello').on('hidden.bs.popover', function () {
  console.log('Popover hidden');
});
</script>
<style>
     body {
      font-family: 'Roboto', sans-serif;
      background-color: #eef2f4; 
      color: #505050;
      line-height: 1.6;
    }
  .container {
    max-width: 1100px;
    margin: auto;
  }
/* 
  .container {
    max-width: 1200px; 
    margin: auto;
    padding: 15px;
  } */

  .nav-button {
    margin-bottom: 20px;
  }
  .btn-outline-info {
    width: 100%;
    padding: 10px;
    margin-bottom: 20px;
  }

  

  .btn-primary {
    background-color: #007bff;
    border-color: #007bff;
  }

  .card {
    margin-bottom: 20px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .card-title {
    color: #333;
  }

  .card-link {
    color: #007bff;
  }

  .table {
    margin-top: 20px;
  }

  @media (max-width: 768px) {
    .container {
      padding: 15px;
    }
  }
  @media (max-width: 768px) {
    .chart-row {
      flex-direction: column;
    }
    .chart-item {
      flex-basis: 100%;
    }
  }
</style>

{% endblock %}

bip/templates/bip/error_page.html
{% extends 'partials/base.html' %} 
{% block content %}
<title>EFBA</title>

<br><br><br>
<div class="container">
    <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'bip:dashboard' student.id %}">Dashboard</a>
    <br/>
  

<div class="container">
       <!--#####################START HERE######################-->
   
       <!-- JUMBOTRON -->
       <div class="jumbotron text-center">
         <h1 class="display-4"> {{user.username }}</h1>
         <p class="lead"> <h1> Must Create Incident first to view the data. Please return to Dashboard </h1></p>
         <hr>
       </div>
   


{% endblock %} 